# adm.toml
#
# Manifest of the adm.database.postgres library. The [publisher] section is
# written by `adm app init` with the publisher's key.

schema = 1

[publisher]
pubkey = "ed25519:base64:ZcfhD3m1jmc/pabbwU8U1XL8wQxCBia6+HCVV14aq50="
repo_salt = "base64:bxaekM1p7xZpd8ktPPPp0G8Al/steX8Ww4sNF/ae9pc="
